# Generated by Django 2.1.3 on 2019-12-23 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auditlog', '0009_convert_json_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logentry',
            name='additional_data',
        ),
    ]
