# Generated by Django 2.1.3 on 2019-12-23 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auditlog', '0010_remove_logentry_additional_data'),
    ]

    operations = [
        migrations.RenameField(
            model_name='logentry',
            old_name='additional_data_new',
            new_name='additional_data',
        ),
    ]
