# Generated by Django 3.2.13 on 2022-05-31 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditlog', '0011_auto_20191223_1115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logentry',
            name='additional_data',
            field=models.JSONField(blank=True, null=True, verbose_name='additional data'),
        ),
    ]
